#include "Options/Soccer.h"

#include "Options/Tools/ButtonPressedAndReleased.h"
#include "Options/Output/HeadMotionRequest/SetHeadPanTilt.h"
#include "Options/HeadControl/LookForward.h"
#include "Options/HeadControl/LookDead.h"
#include "Options/Output/MotionRequest/Stand.h"
#include "Options/Output/MotionRequest/SitDown.h"
#include "Options/GameControl/HandlePenaltyState.h"
#include "Options/GameControl/PlayingState.h"
